[package]
name = "floppa-macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
floppa = { path = "../floppa"}
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.4"
async-trait = "0.1"
twilight-model = "0.15"
